version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musicspace-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./public/images:/usr/share/nginx/html/images
      - ./public/uploads:/usr/share/nginx/html/uploads
    networks:
      - musicspace-network

networks:
  musicspace-network:
    external: true
    name: humamappleteampreject001_musicspace-network
